config/routes.rb
Rails.application.routes.draw do
  resources :conversations do
    member do
      post 'add_message'
    end
  end

  root to: 'page#dashboard'

  namespace :page do
    get 'dashboard'
    get 'about_us'
  end

  get 'profile/:id', to: 'users#show', as: 'users'

  resources :grants
  resources :events
  resources :papers
  resources :collaborations
  devise_for :users, :controllers => { :registrations => 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages

  scope :involved, ->(query) {
    where(inviter_id: query).or(where(invitee_id: query))
  }

  self.per_page = 5

  def self.last_conversations(user_id)
    conversations = involved(user_id)
    conversations = conversations.select {|conversation| conversation.messages.present? }
    conversations.sort! { |conversation| conversation.messages.last.created_at }.last(3)
  end

  def partner(user_id)
    return User.find(invitee_id) if inviter_id == user_id
    User.find(inviter_id)
  end

  def self.seed(n_conversation)
    Message.destroy_all
    Conversation.destroy_all
    users = User.ids - [1]
    n_conversation.times do
      if rand(2) == 1
        inviter_id = 1
        invitee_id = users.sample
      else
        invitee_id = 1
        inviter_id = users.sample
      end
      convo = create!(invitee_id: invitee_id, inviter_id: inviter_id)

      if rand(2) == 1
        convo.messages.create!(sender_id: inviter_id, reciever_id: invitee_id, content: 'I found your problem statement interestings. Want to discuss this over email?')
      end
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :edit, :update, :destroy, :add_message]

  # GET /conversations
  # GET /conversations.json
  def index
    @conversations = Conversation.involved(current_user.id).includes(:messages)
    @users = User.where(id: @conversations.pluck(:inviter_id, :invitee_id).flatten.uniq - [current_user.id])
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
    load_messages
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations
  # POST /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to @conversation, notice: 'Conversation was successfully created.' }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_message
    @conversation.messages.create(message_params)
    load_messages
    respond_to do |format|
      format.html { render :show }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversation_params
      params.permit(:inviter_id, :invitee_id)
    end

    def message_params
      params.permit(:sender_id, :reciever_id, :content)
    end

    def load_messages
      partner_id = [@conversation.inviter_id, @conversation.invitee_id] - [current_user.id]
      @partner = User.find(partner_id.first)
      @messages = Message.where(conversation_id: @conversation.id)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= form_with(model: conversation, local: true) do |form| %>
  <% if conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% conversation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :reciever_id_id %>
    <%= form.text_field :reciever_id_id %>
  </div>

  <div class="field">
    <%= form.label :sender_id_id %>
    <%= form.text_field :sender_id_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/conversations/_messages.html.erb
<% messages.each do |message| %>
  <div class='row'>
    <% if message.sender_id == current_user.id %>
      <% align = 'right' %>
    <% else %>
      <% align = 'left' %>
    <% end %>
    <p style="width: 100%; text-align: <%= align %>;">
      <%= message.content %>
    </p>
  </div>
<% end %>

<%= form_with url: add_message_conversation_path(conversation), remote: true do |f| %>
  <div class="input-group">
    <%= f.hidden_field :reciever_id, value: partner.id %>
    <%= f.hidden_field :sender_id, value: current_user.id %>
    <%= f.text_field :content, class: 'form-control' %>
    <div class="input-group-append">
      <%= f.submit 'Reply', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/conversations/add_message.js.erb
inner_html = ("<%= j render partial: 'messages', locals: {conversation: @conversation, messages: @messages, partner: @partner} %>");
node = document.getElementById('messages')
node.innerHTML = inner_html;

app/views/conversations/contact.html.erb
<div class="main-card mb-3 card mt-4">
  <div class="card-header">
    <div class="card-title">
      Contact
    </div>
    <div style="margin-left: auto">
      <%= link_to 'Back', conversations_path, class: "mb-2 mr-2 btn btn-primary"%>

    </div>
  </div>
  <div class="card-body">
    <%= form_with model: Conversation.new do |form| %>
      <%= form.hidden_field :reciever_id, value: params[:reciever_id] %>
      <%= form.hidden_field :sender_id, value: current_user.id %>
      <div class="field w1 row">
        <div class="col-lg-1 col-md-1"></div>
      </div>

      <div class="field w1 row">
        <div class="col-lg-1 col-md-1"></div>
        <div class="control-label col-lg-3 col-md-3 col-sm-4 col-xs-12">
          <%= form.label :content, 'Message' %>
        </div>
        <div class="input-group col-lg-7 col-md-7 col-sm-8 col-xs-12">
          <%= form.text_field :contact, class: "form-control" %>
        </div>
      </div>

      <div class="actions row">
        <div class="col-lg-1 col-md-1"></div>
        <%= form.submit 'Message', :class => 'mb-2 mr-2  btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<p id="notice"><%= notice %></p>

<div class="main-card mb-3 card mt-4">
  <div class="card-header">
    <div class="card-title">
      Messages
    </div>
  </div>

  <div class="card-body">
    <% @conversations.each do |conversation| %>
      <div class="row">
        <% user = @users.find { |user| [conversation.inviter_id, conversation.invitee_id].include?(user.id)} %>
        <p><%= link_to user.name, conversation_path(conversation) %><br>
        <% if conversation.messages.present? %>
          <% if conversation.messages.last.sender_id == current_user.id %>
            Me: <%= conversation.messages.last.content %><br>
          <% else %>
            Them: <%= conversation.messages.last.content %><br>
          <% end %>
        <% else %>
          No messages sent</p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<p id="notice"><%= notice %></p>
<div class="main-card mb-3 card mt-4">
  <div class="card-header">
    <div class="card-title">
      <%= @partner.name %>
    </div>

    <div style="margin-left: auto">
      <%= link_to 'Back', conversations_path, class: 'mb-2 mr-2 btn btn-primary' %>
    </div>
  </div>

  <div id='messages' class="card-body">
    <%= render partial: 'messages', locals: {conversation: @conversation, messages: @messages, partner: @partner} %>
  </div>
</div>