config/routes.rb
Rails.application.routes.draw do
  resources :conversations do
    member do
      post 'add_message'
    end
  end

  root to: 'page#dashboard'

  namespace :page do
    get 'dashboard'
    get 'about_us'
  end

  get 'profile/:id', to: 'users#show', as: 'users'

  resources :grants
  resources :events
  resources :papers
  resources :collaborations
  devise_for :users, :controllers => { :registrations => 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :institute

  serialize :fields, Array
  serialize :phone_numbers, Array

  filterrific :available_filters => %w[
    with_institute
    with_title
    with_description
    with_certification
    with_fields
  ]

  self.per_page = 10

  scope :with_description, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'description ~* ?' }.join(' OR ')

    where(clause, *terms)
  }

  scope :with_institute, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'name ~* ?' }.join(' OR ')

    institute_ids = Institute.where(clause, *terms)
    where(institute_id: institute_ids)
  }
  scope :with_fields, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'fields ~* ?'}.join(' OR ')

    where(clause, *terms)
  }
  scope :with_title, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'title ~* ?'}.join(' OR ')
    
    where(clause, *terms)
  }

  scope :with_certification, ->(query) {
    return nil if query.blank?
    where(certification: query)
  }

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    (@filterrific = initialize_filterrific(
      Event,
      params[:filterrific]
    )) || return
    @upcoming_events = Event.count
    @institutes_involved = Event.pluck(:institute_id).uniq.count
    @fields_covered = Event.pluck(:fields).flatten.uniq.count
    @events = @filterrific.find.page(params[:page]).includes(:institute)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:institute_id, :title, :description, :fields, :certification, :price, :start_date, :end_date)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :institute_id %>
    <%= form.text_field :institute_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :fields %>
    <%= form.text_area :fields %>
  </div>

  <div class="field">
    <%= form.label :certification %>
    <%= form.check_box :certification %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-6 col-xl-4">
    <div class="card mb-3 widget-content bg-midnight-bloom">
      <div class="widget-content-wrapper text-white">
        <div class="widget-content-left">
          <div class="widget-heading">Upcoming Events</div>
          <div class="widget-subheading"><%= WEB_DEFAULTS[:website_name] %> Research Events</div>
        </div>
        <div class="widget-content-right">
          <div class="widget-numbers text-white"><span><%= @upcoming_events %></span></div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-xl-4">
    <div class="card mb-3 widget-content bg-arielle-smile">
      <div class="widget-content-wrapper text-white">
        <div class="widget-content-left">

          <div class="widget-heading">Institutes Involved</div>
          <div class="widget-subheading">Institutes on <%= WEB_DEFAULTS[:website_name] %></div>
        </div>
        <div class="widget-content-right">
          <div class="widget-numbers text-white"><span><%= @institutes_involved %></span></div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-xl-4">
    <div class="card mb-3 widget-content bg-grow-early">
      <div class="widget-content-wrapper text-white">
        <div class="widget-content-left">
          <div class="widget-heading">Research Interests</div>
          <div class="widget-subheading">Spanning Area of Interests</div>
        </div>
        <div class="widget-content-right">
          <div class="widget-numbers text-white"><span><%= @fields_covered %></span></div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="main-card mb-3 card mt-4">
  <div class="card-header">
    <div class="card-title">
      Events
    </div>
  </div>

  <div class="card-body">

    <div class='filters'>
      <%= form_for_filterrific @filterrific do |f| %>
        <div class="mb-2 w1 mr-sm-2 mb-sm-0 position-relative form-group row">
          <div class="col-lg-1 col-md-1"></div>
          <div class="control-label col-lg-3 col-md-3 col-sm-4 col-xs-12">
            <%= f.label :with_title, 'Search by Title' %>
          </div>
          <div class="input-group col-lg-7 col-md-7 col-sm-8 col-xs-12">
            <%= f.text_field :with_title, class: "form-control" %></div>
        </div>

        <div class="mb-2  w1 mr-sm-2 mb-sm-0 position-relative form-group row">
          <div class="col-lg-1 col-md-1"></div>
          <div class="control-label col-lg-3 col-md-3 col-sm-4 col-xs-12">
            <%= f.label :with_description, 'Search by Description' %>
          </div>
          <div class="input-group col-lg-7 col-md-7 col-sm-8 col-xs-12">

            <%= f.text_field :with_description, class: "form-control" %>
          </div>
        </div>

        <div class="mb-2 w1 mr-sm-2 mb-sm-0 position-relative form-group row">
          <div class="col-lg-1 col-md-1"></div>

          <div class="control-label col-lg-3 col-md-3 col-sm-4 col-xs-12">
            <%= f.label :with_fields, 'Search by Relevant Fields' %>
          </div>
          <div class="input-group col-lg-7 col-md-7 col-sm-8 col-xs-12">

            <%= f.text_field :with_fields, class: "form-control" %>
          </div>
        </div>

        <div class="mb-2 w1 mr-sm-2 mb-sm-0 position-relative form-group row">
          <div class="col-lg-1 col-md-1"></div>

          <div class="control-label col-lg-3 col-md-3 col-sm-4 col-xs-12">
            <%= f.label :with_author, 'Search by Creator' %>
          </div>
          <div class="input-group col-lg-7 col-md-7 col-sm-8 col-xs-12">
            <%= f.text_field :with_author, class: "form-control" %>
          </div>
        </div>

        <div class="row" style="margin-top: 2em">
          <div class="col-lg-1 col-md-1"></div>
          <%= f.submit 'Search', class: "mb-2 mr-2  btn btn-primary" %>
        </div>
      <% end %>

      <div class='list'>
        <table class="mb-0 table table-striped table-hover">
          <thead>
          <tr>
            <th>Title</th>
            <th>Institute</th>
            <th>Certified</th>
            <th>Price</th>
            <th>Fields</th>
            <th>Start Date</th>
            <th>End Date</th>
          </tr>
          </thead>

          <tbody>
          <% @events.each do |event| %>
            <tr>
              <td><%= link_to event.title, event_path(event) %></td>
              <td><%= event.institute.name %></td>
              <td>
                <% if event.certification %>
                  <div class="mb-2 mr-2 badge badge-success">
                    Yes
                  </div>
                <% else %>
                  <div class="mb-2 mr-2 badge badge-warning">
                    No
                  </div>
                <% end %>
              </td>
              <td>Rs. <%= event.price %></td>
              <td>
                <% event.fields.each do |evnt| %>
                  <div class="mb-2 mr-2 badge badge-secondary">
                    <%= evnt %>
                  </div>
                  <%end %>
              </td>
              <td><%= pretty_date(event.start_date) %></td>
              <td><%= pretty_date(event.end_date) %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <%= render partial: 'partials/pagination', locals: {objects: @events} %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="main-card mb-3 card mt-4">
  <div class="card-header">
    <div class="card-title">
      Event Details
    </div>

    <div style="margin-left: auto">

      <%= link_to 'Edit', edit_event_path(@event), class: "mb-2 mr-2 btn-transition btn btn-outline-warning"  %>
      <%= link_to 'Back', events_path, class: "mb-2 mr-2  btn btn-primary"  %>
    </div>
  </div>
  <div class="card-body">
    <p>
      <strong>Institute:</strong>
      <%= @event.institute %>
    </p>

    <p>
      <strong>Title:</strong>
      <%= @event.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @event.description %>
    </p>

    <p>
      <strong>Fields:</strong>
      <%= @event.fields %>
    </p>

    <p>
      <strong>Certification:</strong>
      <%= @event.certification %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @event.price %>
    </p>

    <p>
      <strong>Start date:</strong>
      <%= @event.start_date %>
    </p>

    <p>
      <strong>End date:</strong>
      <%= @event.end_date %>
    </p>


  </div>
</div>