config/routes.rb
Rails.application.routes.draw do
  resources :conversations do
    member do
      post 'add_message'
    end
  end

  root to: 'page#dashboard'

  namespace :page do
    get 'dashboard'
    get 'about_us'
  end

  get 'profile/:id', to: 'users#show', as: 'users'

  resources :grants
  resources :events
  resources :papers
  resources :collaborations
  devise_for :users, :controllers => { :registrations => 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
end

app/models/collaboration.rb
class Collaboration < ApplicationRecord
  belongs_to :user

  serialize :fields, Array

  filterrific :available_filters => %w[
    with_title
    with_description
    with_author
    with_fields
  ]

  self.per_page = 10

  scope :with_title, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'title ~* ?' }.join(' OR ')

    where(clause, *terms)
  }

  scope :with_description, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'description ~* ?' }.join(' OR ')

    where(clause, *terms)
  }

  scope :with_author, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'name ~* ? OR email ~* ?' }.join(' OR ')

    user_ids = User.where(clause, *(terms * 2)).ids

    where(user_id: user_ids)
  }
  scope :with_fields, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'fields ~* ?' }.join(' OR ')

    where(clause, *terms)
  }
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages

  scope :involved, ->(query) {
    where(inviter_id: query).or(where(invitee_id: query))
  }

  self.per_page = 5

  def self.last_conversations(user_id)
    conversations = involved(user_id)
    conversations = conversations.select {|conversation| conversation.messages.present? }
    conversations.sort! { |conversation| conversation.messages.last.created_at }.last(3)
  end

  def partner(user_id)
    return User.find(invitee_id) if inviter_id == user_id
    User.find(inviter_id)
  end

  def self.seed(n_conversation)
    Message.destroy_all
    Conversation.destroy_all
    users = User.ids - [1]
    n_conversation.times do
      if rand(2) == 1
        inviter_id = 1
        invitee_id = users.sample
      else
        invitee_id = 1
        inviter_id = users.sample
      end
      convo = create!(invitee_id: invitee_id, inviter_id: inviter_id)

      if rand(2) == 1
        convo.messages.create!(sender_id: inviter_id, reciever_id: invitee_id, content: 'I found your problem statement interestings. Want to discuss this over email?')
      end
    end
  end
end

app/models/degree.rb
class Degree < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :institute

  serialize :fields, Array
  serialize :phone_numbers, Array

  filterrific :available_filters => %w[
    with_institute
    with_title
    with_description
    with_certification
    with_fields
  ]

  self.per_page = 10

  scope :with_description, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'description ~* ?' }.join(' OR ')

    where(clause, *terms)
  }

  scope :with_institute, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'name ~* ?' }.join(' OR ')

    institute_ids = Institute.where(clause, *terms)
    where(institute_id: institute_ids)
  }
  scope :with_fields, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'fields ~* ?'}.join(' OR ')

    where(clause, *terms)
  }
  scope :with_title, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'title ~* ?'}.join(' OR ')
    
    where(clause, *terms)
  }

  scope :with_certification, ->(query) {
    return nil if query.blank?
    where(certification: query)
  }

end

app/models/grant.rb
class Grant < ApplicationRecord
  serialize :fields, Array

  filterrific :available_filters => %w[
    with_title
    with_fields
    with_description
    before_deadline
  ]

  self.per_page = 10

  scope :with_title, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'title ~* ?' }.join(' OR ')

    where(clause, *terms)
  }
  scope :with_fields, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'fields ~* ?'}.join(' OR ')

    where(clause, *terms)
  }
  scope :with_description, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'description ~* ?'}.join(' OR ')
    
    where(clause, *terms)
  }

  scope :before_deadline, ->(query) {
    where('submission_deadline <= ?', query)
  }
end

app/models/institute.rb
class Institute < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
end

app/models/paper.rb
class Paper < ApplicationRecord
  belongs_to :user
  belongs_to :institute

  serialize :fields, Array

  filterrific :available_filters => %w[
    with_journal_link
    with_institute
    with_fields
    with_abstract
    with_author
  ]

  self.per_page = 10

  scope :with_journal_link, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'journal_link ~* ?' }.join(' OR ')

    where(clause, *terms)
  }

  scope :with_institute, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'name ~* ?' }.join(' OR ')

    institute_ids = Institute.where(clause, *terms)
    where(institute_id: institute_ids)
  }
  scope :with_fields, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'fields ~* ?'}.join(' OR ')

    where(clause, *terms)
  }
  scope :with_abstract, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'abstract ~* ?'}.join(' OR ')
    
    where(clause, *terms)
  }
  scope :with_author, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'name ~* ? OR email ~* ?'}.join(' OR ')

    user_ids = User.where(clause, *(terms * 2)).ids
    where(user_id: user_ids)
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :institute
  belongs_to :degree
  belongs_to :branch

  serialize :interests, Array
  serialize :phone_numbers, Array
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]
  layout 'about_us', only: [:about_us]

  def dashboard
    @featured_paper = Paper.find(12)
    @last_conversations = Conversation.last_conversations(current_user.id)
  end

  def about_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pretty_date(date)
    date.strftime('%b %d, %Y')
  end
end

app/helpers/archtest_helper.rb
module ArchtestHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/grants_helper.rb
module GrantsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/page/dashboard.html.erb
<div class="row">
  <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
    <div class="mb-3 main-card mt-4 card text-white" style="background-color: rgb(51, 51, 51); border-color: rgb(51, 51, 51);">
      <div class="card-header"><%= @featured_paper.title %></div>
      <div class="card-body">
        <em><h5 class="text-white card-title">Featured Paper</h5></em>
        <p style="width: 50%;">
          <%= @featured_paper.abstract %>
        </p>
      </div>
      <div class="card-footer">
        <%= link_to 'Read More', paper_path(@featured_paper) %>
      </div>
    </div>
    <div class="main-card mb-3 card">
      <div class="card-body">
        <h5 class="card-title" style="padding-bottom: 1em;"><%= link_to 'Messages', conversations_path %></h5>
        <ul class="list-group">
          <% @last_conversations.each do |conversation| %>
            <li class='list-group-item'>
              <p class='list-group-item-heading'><%= conversation.partner(current_user.id).name %></p>
              <em><p class='list-group-item-text'><%= conversation.messages.last.content %></p></em>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
    <div class="main-card mb-3 card mt-4">

      <div class="card-body">


        <h1 style="font-family: 'Lobster', cursive;">
          <%= current_user.name %>
        </h1>
        <h3>
          Researcher
        </h3>
        <h5>
          <%= current_user.institute.name %>
        </h5>
        <strong>Email :</strong> <%= current_user.email %>
        <br>
        <strong>Phone Number:</strong>
        <% current_user.phone_numbers.each do |phn| %>
            <%= phn %>&nbsp;&nbsp;
        <%end %>
        <br>
        <strong>Interests:</strong>
        <ul>
          <% current_user.interests.each do |intr| %>
            <li>
              <%= intr %>
            </li>
          <%end %>
        </ul>
        <strong>Education:</strong>
        <ul>
          <% current_user.education.each do |edu| %>
            <li>
              <%= edu[2] %> - <%= edu[0] %> at <%= edu[1] %>
            </li>
          <%end %>
        </ul>
        <strong>Achievements:</strong>
        <ul>
          <% current_user.achievements.each do |ach| %>
            <li>
              (<%= ach[1] %>) - <%= ach[0] %>
            </li>
            <%end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/page/index.html.erb
<!DOCTYPE HTML>
<!--
	Solid State by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->

<html>
<head>
  <title><%= WEB_DEFAULTS[:website_name] %>- <%= WEB_DEFAULTS[:website_full] %></title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
  <link rel="stylesheet" href="/main/assets/css/main.css" />
  <style>
    .field{
      padding-top: 0.5em;
      padding-bottom: 0.5em;
    }
  </style>
  <noscript><link rel="stylesheet" href="/main/assets/css/noscript.css" /></noscript>
</head>
<body class="is-preload">

<!-- Page Wrapper -->
<div id="page-wrapper">

  <!-- Header -->
  <header id="header" class="alt">
    <h1><a href="\"><%= WEB_DEFAULTS[:website_name] %></a></h1>
    <nav>
      <a href="#menu">Menu</a>
    </nav>
  </header>

  <!-- Menu -->
  <nav id="menu">
    <div class="inner">
      <h2>Menu</h2>
      <ul class="links">
        <li><a href="index.html">Home</a></li>
        <li><a href="generic.html">Generic</a></li>
        <li><a href="elements.html">Elements</a></li>
        <li><a href="#">Log In</a></li>
        <li><a href="#">Sign Up</a></li>
      </ul>
      <a href="#" class="close">Close</a>
    </div>
  </nav>

  <!-- Banner -->
  <section id="banner">
    <div class="inner">
      <div class="logo"><span class="icon fa-gem"></span></div>
      <h2><%= WEB_DEFAULTS[:website_name] %></h2>
      <p><%= WEB_DEFAULTS[:website_description] %></p>
    </div>
  </section>

  <!-- Wrapper -->
  <section id="wrapper">

    <!-- One -->
    <section id="one" class="wrapper spotlight style1">
      <div class="inner">
        <a href="#" class="image"><img src="images/pic01.jpg" alt="" /></a>
        <div class="content">
          <h2 class="major">Collaboration</h2>
          <p>We find that many researchers are not able to find a perfect partner for their job. This platform aides those people.</p>
          <a href="#" class="special">Learn more</a>
        </div>
      </div>
    </section>

    <!-- Two -->
    <section id="two" class="wrapper alt spotlight style2">
      <div class="inner">
        <a href="#" class="image"><img src="images/pic02.jpg" alt="" /></a>
        <div class="content">
          <h2 class="major">Events</h2>
          <p>Lorem ipsum dolor sit amet, etiam lorem adipiscing elit. Cras turpis ante, nullam sit amet turpis non, sollicitudin posuere urna. Mauris id tellus arcu. Nunc vehicula id nulla dignissim dapibus. Nullam ultrices, neque et faucibus viverra, ex nulla cursus.</p>
          <a href="#" class="special">Learn more</a>
        </div>
      </div>
    </section>

    <!-- Three -->
    <section id="three" class="wrapper spotlight style3">
      <div class="inner">
        <a href="#" class="image"><img src="images/pic03.jpg" alt="" /></a>
        <div class="content">
          <h2 class="major">Nullam dignissim</h2>
          <p>Lorem ipsum dolor sit amet, etiam lorem adipiscing elit. Cras turpis ante, nullam sit amet turpis non, sollicitudin posuere urna. Mauris id tellus arcu. Nunc vehicula id nulla dignissim dapibus. Nullam ultrices, neque et faucibus viverra, ex nulla cursus.</p>
          <a href="#" class="special">Learn more</a>
        </div>
      </div>
    </section>

    <!-- Four -->
    <section id="four" class="wrapper alt style1">
      <div class="inner">
        <h2 class="major">Sign Up</h2>
        <div class="fields">
          <div class="field">
            <label for="name">Name</label>
            <input type="text" name="name" id="name" />
          </div>
          <div class="field">
            <label for="email">Email</label>
            <input type="email" name="email" id="email" />
          </div>
          <div class="field">
            <label for="message">Message</label>
            <textarea name="message" id="message" rows="4"></textarea>
          </div>
          <a href="#" class="button primary">Sign Up!</a>
          <a href="#" class="button">Login</a>
      </div>
      </div>
    </section>

  </section>

  <!-- Footer -->
  <section id="footer">
    <div class="inner">
      <h2 class="major">Get in touch</h2>
      <p>We'd love to hear from you!</p>
      <ul class="contact">
        <li class="icon solid fa-home">
          Untitled Inc<br />
          1234 Somewhere Road Suite #2894<br />
          Nashville, TN 00000-0000
        </li>
        <li class="icon solid fa-phone">(000) 000-0000</li>
        <li class="icon solid fa-envelope"><a href="#">information@untitled.tld</a></li>
        <li class="icon brands fa-twitter"><a href="#">twitter.com/untitled-tld</a></li>
        <li class="icon brands fa-facebook-f"><a href="#">facebook.com/untitled-tld</a></li>
        <li class="icon brands fa-instagram"><a href="#">instagram.com/untitled-tld</a></li>
      </ul>
      <ul class="copyright">
        <li>&copy; NIT Conclave Hackathon Project by <a href="https://abhishek2718.github.io">Abhishek Kumar</a> and <a href="https://nirmalhk7.github.io">Nirmal Khedkar</a>.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
      </ul>
    </div>
  </section>

</div>

<!-- Scripts -->
<script src="/main/assets/js/jquery.min.js"></script>
<script src="/main/assets/js/jquery.scrollex.min.js"></script>
<script src="/main/assets/js/browser.min.js"></script>
<script src="/main/assets/js/breakpoints.min.js"></script>
<script src="/main/assets/js/util.js"></script>
<script src="/main/assets/js/main.js"></script>

</body>
</html>

app/views/partials/_footer.html.erb
<div class="app-wrapper-footer">
  <div class="app-footer">
    <div class="app-footer__inner">
      <div class="app-footer-left">

            Made By <a href="https://abhishek2718.github.io" class="nav-link" style="padding-left: 5px!important;padding-right: 5px!important;">Abhishek Kumar</a>
       and <a href="https://nirmalhk7.github.io"class="nav-link" style="padding-left: 5px!important;">Nirmal Khedkar</a>


      </div>
      <div class="app-footer-right">
        <ul class="nav">
          <li class="nav-item">
            <div class="mb-2 mr-2 badge badge-light">
              Built at NIT Conclave 2019
            </div>
          </li>

        </ul>
      </div>
    </div>
  </div>
</div>

app/views/partials/_loader.html.erb
<div class="loader">
  <div class="loader-outter"></div>
  <div class="loader-inner" style="background-image: url('/loader.gif');"></div>
</div>

app/views/partials/_navbar.html.erb
<div class="app-header header-shadow">
  <div class="app-header__logo">
    <div class="logo-src" style="font-family: 'Hepta Slab', serif;font-size: 1rem;
    "><b><%= WEB_DEFAULTS[:website_name] %></b></div>
    <div class="header__pane ml-auto">
      <div>

      </div>
    </div>
  </div>

  <div class="app-header__mobile-menu">
    <div>
      <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
      </button>
    </div>
  </div>
  <div class="app-header__menu">
                <span>
                    <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                        <span class="btn-icon-wrapper">
                            <i class="fa fa-ellipsis-v fa-w-6"></i>
                        </span>
                    </button>
                </span>
  </div>
  <div class="app-header__content">
    <div class="app-header-left">
      <!-- 
      <div class="search-wrapper">
        <div class="input-holder">
          <input type="text" class="search-input" placeholder="Type to search">
          <button class="search-icon"><span></span></button>
        </div>
        <button class="close"></button>
      </div>
      -->

      <% if user_signed_in? %>
        <ul class="header-menu nav">
          <li class="dropdown nav-item">
            <%= link_to page_dashboard_path, class: "nav-link" do %>
              <i class='nav-link-icon fa fa-user'> </i>Dashboard
            <% end %>
          </li>

          <li class="dropdown nav-item">
            <%= link_to collaborations_path, class: "nav-link" do %>
              <i class='nav-link-icon fa fa-user'> </i>Collaboration
            <% end %>
          </li>

          <li class="dropdown nav-item">
            <%= link_to events_path, class: "nav-link" do %>
              <i class='nav-link-icon fa fa-users'> </i>Events
            <% end %>
          </li>

          <li class="dropdown nav-item">
            <%= link_to papers_path, class: "nav-link" do %>
              <i class='nav-link-icon fa fa-th-list'> </i>Papers
            <% end %>
          </li>

          <li class="dropdown nav-item">
            <%= link_to grants_path, class: "nav-link" do %>
              <i class='nav-link-icon fa fa-industry'> </i>Grants
            <% end %>
          </li>

          <li class="dropdown nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
              <i class='nav-link-icon fa fa-lock'> </i>Log Out
            <% end %>
          </li>
        </ul>
      <% end %>

    </div>
    <div class="app-header-right">
      <div class="header-btn-lg pr-0">
        <div class="widget-content p-0">
          <div class="widget-content-wrapper">
            <div class="widget-content-left">
              <div class="btn-group">
                <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="p-0 btn">
                  <div class="row">

                  </div>
                  <% if current_user %>
                    <div class="widget-heading" style="text-align: right">
                      <%= current_user.name %>
                    </div>
                    <div class="widget-subheading" style="text-align: right">
                      <%= current_user.institute.name %>
                    </div>
                  <% end %>
                </a>

              </div>
            </div>
            <div class="widget-content-left  ml-3 header-user-info">

            </div>
            <div class="widget-content-right header-user-info ml-3">
              <button type="button" class="btn-shadow p-1 btn btn-primary btn-sm show-toastr-example">
                <i class="fa text-white fa-calendar pr-1 pl-1"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_pagination.html.erb
<style>
  .digg_pagination {
    display: flex;
    padding-left: 0;
    list-style: none;
    border-radius: .25rem
    /* self-clearing method: */ }
  .digg_pagination a, .digg_pagination span, .digg_pagination em {
    padding: 0.2em 0.5em;
    display: block;
    float: left;
    margin-right: 1px; }
  .digg_pagination .disabled {
    color: #999999;
    border: 1px solid #dddddd; }
  .digg_pagination .current {
    font-style: normal;
    font-weight: bold;
    background: #2e6ab1;
    color: white;
    border: 1px solid #2e6ab1; }
  .digg_pagination a {
    text-decoration: none;
    color: #105cb6;
    border: 1px solid #9aafe5; }
  .digg_pagination a:hover, .digg_pagination a:focus {
    color: #000033;
    border-color: #000033; }
  .digg_pagination .page_info {
    background: #2e6ab1;
    color: white;
    padding: 0.4em 0.6em;
    width: 22em;
    margin-bottom: 0.3em;
    text-align: center; }
  .digg_pagination .page_info b {
    color: #000033;
    background: #6aa6ed;
    padding: 0.1em 0.25em; }
  .digg_pagination:after {
    content: ".";
    display: block;
    height: 0;
    clear: both;
    visibility: hidden; }
  * html .digg_pagination {
    height: 1%; }
  *:first-child + html .digg_pagination {
    overflow: hidden; }

  .apple_pagination {
    background: #f1f1f1;
    border: 1px solid #e5e5e5;
    text-align: center;
    padding: 1em;
    cursor: default; }
  .apple_pagination a, .apple_pagination span {
    padding: 0.2em 0.3em; }
  .apple_pagination .disabled {
    color: #aaaaaa; }
  .apple_pagination .current {
    font-style: normal;
    font-weight: bold;
    background-color: #bebebe;
    display: inline-block;
    width: 1.4em;
    height: 1.4em;
    line-height: 1.5;
    -moz-border-radius: 1em;
    -webkit-border-radius: 1em;
    border-radius: 1em;
    text-shadow: rgba(255, 255, 255, 0.8) 1px 1px 1px; }
  .apple_pagination a {
    text-decoration: none;
    color: black; }
  .apple_pagination a:hover, .apple_pagination a:focus {
    text-decoration: underline; }

  .flickr_pagination {
    text-align: center;
    padding: 0.3em;
    cursor: default; }
  .flickr_pagination a, .flickr_pagination span, .flickr_pagination em {
    padding: 0.2em 0.5em; }
  .flickr_pagination .disabled {
    color: #aaaaaa; }
  .flickr_pagination .current {
    font-style: normal;
    font-weight: bold;
    color: #ff0084; }
  .flickr_pagination a {
    border: 1px solid #dddddd;
    color: #0063dc;
    text-decoration: none; }
  .flickr_pagination a:hover, .flickr_pagination a:focus {
    border-color: #003366;
    background: #0063dc;
    color: white; }
  .flickr_pagination .page_info {
    color: #aaaaaa;
    padding-top: 0.8em; }
  .flickr_pagination .previous_page, .flickr_pagination .next_page {
    border-width: 2px; }
  .flickr_pagination .previous_page {
    margin-right: 1em; }
  .flickr_pagination .next_page {
    margin-left: 1em; }
</style>
<div class="digg_pagination" style="padding-top: 2em">
  <%= will_paginate objects %>&nbsp;
</div>

app/views/partials/_sidebar.html.erb
<div class="scrollbar-sidebar">
  <div class="app-sidebar__inner">
    <ul class="vertical-nav-menu">
      <li class="app-sidebar__heading">Dashboards</li>
      <li>
        <a href="index.html">
          <i class="metismenu-icon pe-7s-rocket"></i>
          Dashboard Example 1
        </a>
      </li>
      <li class="app-sidebar__heading">UI Components</li>
      <li>
        <a href="#">
          <i class="metismenu-icon pe-7s-diamond"></i>
          Elements
          <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
        </a>
        <ul>
          <li>
            <a href="elements-buttons-standard.html">
              <i class="metismenu-icon"></i>
              Buttons
            </a>
          </li>
          <li>
            <a href="elements-dropdowns.html">
              <i class="metismenu-icon">
              </i>Dropdowns
            </a>
          </li>
          <li>
            <a href="elements-icons.html">
              <i class="metismenu-icon">
              </i>Icons
            </a>
          </li>
          <li>
            <a href="elements-badges-labels.html">
              <i class="metismenu-icon">
              </i>Badges
            </a>
          </li>
          <li>
            <a href="elements-cards.html">
              <i class="metismenu-icon">
              </i>Cards
            </a>
          </li>
          <li>
            <a href="elements-list-group.html">
              <i class="metismenu-icon">
              </i>List Groups
            </a>
          </li>
          <li>
            <a href="elements-navigation.html">
              <i class="metismenu-icon">
              </i>Navigation Menus
            </a>
          </li>
          <li>
            <a href="elements-utilities.html">
              <i class="metismenu-icon">
              </i>Utilities
            </a>
          </li>
        </ul>
      </li>
      <li>
        <a href="#">
          <i class="metismenu-icon pe-7s-car"></i>
          Components
          <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
        </a>
        <ul>
          <li>
            <a href="components-tabs.html">
              <i class="metismenu-icon">
              </i>Tabs
            </a>
          </li>
          <li>
            <a href="components-accordions.html">
              <i class="metismenu-icon">
              </i>Accordions
            </a>
          </li>
          <li>
            <a href="components-notifications.html">
              <i class="metismenu-icon">
              </i>Notifications
            </a>
          </li>
          <li>
            <a href="components-modals.html">
              <i class="metismenu-icon">
              </i>Modals
            </a>
          </li>
          <li>
            <a href="components-progress-bar.html">
              <i class="metismenu-icon">
              </i>Progress Bar
            </a>
          </li>
          <li>
            <a href="components-tooltips-popovers.html">
              <i class="metismenu-icon">
              </i>Tooltips &amp; Popovers
            </a>
          </li>
          <li>
            <a href="components-carousel.html">
              <i class="metismenu-icon">
              </i>Carousel
            </a>
          </li>
          <li>
            <a href="components-calendar.html">
              <i class="metismenu-icon">
              </i>Calendar
            </a>
          </li>
          <li>
            <a href="components-pagination.html">
              <i class="metismenu-icon">
              </i>Pagination
            </a>
          </li>
          <li>
            <a href="components-scrollable-elements.html">
              <i class="metismenu-icon">
              </i>Scrollable
            </a>
          </li>
          <li>
            <a href="components-maps.html">
              <i class="metismenu-icon">
              </i>Maps
            </a>
          </li>
        </ul>
      </li>
      <li>
        <a href="tables-regular.html">
          <i class="metismenu-icon pe-7s-display2"></i>
          Tables
        </a>
      </li>
      <li class="app-sidebar__heading">Widgets</li>
      <li>
        <a href="dashboard-boxes.html">
          <i class="metismenu-icon pe-7s-display2"></i>
          Dashboard Boxes
        </a>
      </li>
      <li class="app-sidebar__heading">Forms</li>
      <li>
        <a href="forms-controls.html" class="mm-active">
          <i class="metismenu-icon pe-7s-mouse">
          </i>Forms Controls
        </a>
      </li>
      <li>
        <a href="forms-layouts.html">
          <i class="metismenu-icon pe-7s-eyedropper">
          </i>Forms Layouts
        </a>
      </li>
      <li>
        <a href="forms-validation.html">
          <i class="metismenu-icon pe-7s-pendrive">
          </i>Forms Validation
        </a>
      </li>
      <li class="app-sidebar__heading">Charts</li>
      <li>
        <a href="charts-chartjs.html">
          <i class="metismenu-icon pe-7s-graph2">
          </i>ChartJS
        </a>
      </li>
      <li class="app-sidebar__heading">PRO Version</li>
      <li>
        <a href="https://dashboardpack.com/theme-details/architectui-dashboard-html-pro/" target="_blank">
          <i class="metismenu-icon pe-7s-graph2">
          </i>
          Upgrade to PRO
        </a>
      </li>
    </ul>
  </div>
</div>