config/routes.rb
Rails.application.routes.draw do
  resources :conversations do
    member do
      post 'add_message'
    end
  end

  root to: 'page#dashboard'

  namespace :page do
    get 'dashboard'
    get 'about_us'
  end

  get 'profile/:id', to: 'users#show', as: 'users'

  resources :grants
  resources :events
  resources :papers
  resources :collaborations
  devise_for :users, :controllers => { :registrations => 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/collaboration.rb
class Collaboration < ApplicationRecord
  belongs_to :user

  serialize :fields, Array

  filterrific :available_filters => %w[
    with_title
    with_description
    with_author
    with_fields
  ]

  self.per_page = 10

  scope :with_title, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'title ~* ?' }.join(' OR ')

    where(clause, *terms)
  }

  scope :with_description, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'description ~* ?' }.join(' OR ')

    where(clause, *terms)
  }

  scope :with_author, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'name ~* ? OR email ~* ?' }.join(' OR ')

    user_ids = User.where(clause, *(terms * 2)).ids

    where(user_id: user_ids)
  }
  scope :with_fields, ->(query) {
    return nil if query.blank?
    terms = query.split(/\s+/)
    clause = terms.map { 'fields ~* ?' }.join(' OR ')

    where(clause, *terms)
  }
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  before_action :set_collaboration, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /collaborations
  # GET /collaborations.json
  def index
    (@filterrific = initialize_filterrific(
      Collaboration,
      params[:filterrific]
    )) || return
    @collaborations_count = Collaboration.count
    @scholar_count = Collaboration.pluck(:user_id).uniq.count
    @fields_covered = Collaboration.pluck(:fields).flatten.uniq.count
    @collaborations = @filterrific.find.page(params[:page]).includes(:user)
  end

  # GET /collaborations/1
  # GET /collaborations/1.json
  def show
  end

  # GET /collaborations/new
  def new
    @collaboration = Collaboration.new
  end

  # GET /collaborations/1/edit
  def edit
  end

  # POST /collaborations
  # POST /collaborations.json
  def create
    creation_params = collaboration_params
    creation_params[:fields] = serialize_to_array(collaboration_params[:fields])
    creation_params[:user] = current_user
    @collaboration = Collaboration.new(creation_params)

    respond_to do |format|
      if @collaboration.save
        format.html { redirect_to @collaboration, notice: 'Collaboration was successfully created.' }
        format.json { render :show, status: :created, location: @collaboration }
      else
        format.html { render :new }
        format.json { render json: @collaboration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collaborations/1
  # PATCH/PUT /collaborations/1.json
  def update
    respond_to do |format|
      if @collaboration.update(collaboration_params)
        format.html { redirect_to @collaboration, notice: 'Collaboration was successfully updated.' }
        format.json { render :show, status: :ok, location: @collaboration }
      else
        format.html { render :edit }
        format.json { render json: @collaboration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collaborations/1
  # DELETE /collaborations/1.json
  def destroy
    @collaboration.destroy
    respond_to do |format|
      format.html { redirect_to collaborations_url, notice: 'Collaboration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collaboration
      @collaboration = Collaboration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collaboration_params
      params.require(:collaboration).permit(:user_id, :title, :description, :fields)
    end
end

app/helpers/collaborations_helper.rb
module CollaborationsHelper
end

app/views/collaborations/_form.html.erb
<%= form_with(model: collaboration, local: true) do |form| %>
  <% if collaboration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collaboration.errors.count, "error") %> prohibited this collaboration from being saved:</h2>

      <ul>
        <% collaboration.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field w1 row">
    <div class="col-lg-1 col-md-1"></div>

  </div>

  <div class="field w1 row">
    <div class="col-lg-1 col-md-1"></div>
    <div class="control-label col-lg-3 col-md-3 col-sm-4 col-xs-12">
      <%= form.label :title %>
    </div>
    <div class="input-group col-lg-7 col-md-7 col-sm-8 col-xs-12">
      <%= form.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="field w1 row">
    <div class="col-lg-1 col-md-1"></div>
    <div class="control-label col-lg-3 col-md-3 col-sm-4 col-xs-12">
      <%= form.label :description %>
    </div>
    <div class="input-group col-lg-7 col-md-7 col-sm-8 col-xs-12">
      <%= form.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="field w1 row">
    <div class="col-lg-1 col-md-1"></div>
      <div class="control-label col-lg-3 col-md-3 col-sm-4 col-xs-12">
        <%= form.label :fields %><br />
        <em>Seperate multiple fields using semi-colon</em>
      </div>

    <div class="input-group col-lg-7 col-md-7 col-sm-8 col-xs-12">
      <%= form.text_area :fields, class: "form-control", value: collaboration.fields.join('; ') %>
    </div>
  </div>

  <div class="actions row">
    <div class="col-lg-1 col-md-1"></div>
    <%= form.submit 'Submit Request', :class => 'mb-2 mr-2  btn btn-success' %>
  </div>
<% end %>

app/views/collaborations/edit.html.erb
<div class="main-card mb-3 card mt-4">
  <div class="card-header">
    <div class="card-title">
      Editing Collaboration Request
    </div>
    <div style="margin-left: auto">
      <%= link_to 'Show', @collaboration, class: "mb-2 mr-2  btn btn-primary"   %>
      <%= link_to 'Back', collaborations_path, class: "mb-2 mr-2 btn-transition btn btn-outline-primary"   %>
    </div>
  </div>
  <div class="card-body">

    <%= render 'form', collaboration: @collaboration %>
  </div>
</div>

app/views/collaborations/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-6 col-xl-4">
    <div class="card mb-3 widget-content bg-midnight-bloom">
      <div class="widget-content-wrapper text-white">
        <div class="widget-content-left">
          <div class="widget-heading">Possible Collaborations</div>
          <div class="widget-subheading"><%= WEB_DEFAULTS[:website_name] %> Registered Researchers</div>
        </div>
        <div class="widget-content-right">
          <div class="widget-numbers text-white"><span><%= @collaborations_count %></span></div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-xl-4">
    <div class="card mb-3 widget-content bg-arielle-smile">
      <div class="widget-content-wrapper text-white">
        <div class="widget-content-left">

          <div class="widget-heading">Research Scholars Involved</div>
          <div class="widget-subheading">Researchers on <%= WEB_DEFAULTS[:website_name] %></div>
        </div>
        <div class="widget-content-right">
          <div class="widget-numbers text-white"><span><%= @scholar_count %></span></div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-xl-4">
    <div class="card mb-3 widget-content bg-grow-early">
      <div class="widget-content-wrapper text-white">
        <div class="widget-content-left">
          <div class="widget-heading">Research Interests</div>
          <div class="widget-subheading">Spanning Area of Interests</div>
        </div>
        <div class="widget-content-right">
          <div class="widget-numbers text-white"><span><%= @fields_covered %></span></div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="main-card mb-3 card mt-4">
  <div class="card-header">
    <div class="card-title">
      Collaboration Requests
    </div>
    <div style="margin-left: auto">
      <%= link_to 'New Collaboration Request', new_collaboration_path, class: "mb-2 mr-2  btn btn-primary" %>
    </div>
  </div>
  <div class="card-body">
    <div class='filters'>
      <%= form_for_filterrific @filterrific do |f| %>
        <div class="mb-2 w1 mr-sm-2 mb-sm-0 position-relative form-group row">
          <div class="col-lg-1 col-md-1"></div>
          <div class="control-label col-lg-3 col-md-3 col-sm-4 col-xs-12">
            <%= f.label :with_title, 'Search by Title' %>
          </div>
          <div class="input-group col-lg-7 col-md-7 col-sm-8 col-xs-12">
            <%= f.text_field :with_title, class: "form-control" %></div>
        </div>

        <div class="mb-2  w1 mr-sm-2 mb-sm-0 position-relative form-group row">
          <div class="col-lg-1 col-md-1"></div>
          <div class="control-label col-lg-3 col-md-3 col-sm-4 col-xs-12">
          <%= f.label :with_description, 'Search by Description' %>
          </div>
          <div class="input-group col-lg-7 col-md-7 col-sm-8 col-xs-12">

          <%= f.text_field :with_description, class: "form-control" %>
          </div>
        </div>

        <div class="mb-2 w1 mr-sm-2 mb-sm-0 position-relative form-group row">
          <div class="col-lg-1 col-md-1"></div>

          <div class="control-label col-lg-3 col-md-3 col-sm-4 col-xs-12">
            <%= f.label :with_fields, 'Search by Relevant Fields' %>
          </div>
          <div class="input-group col-lg-7 col-md-7 col-sm-8 col-xs-12">

          <%= f.text_field :with_fields, class: "form-control" %>
          </div>
        </div>

        <div class="mb-2 w1 mr-sm-2 mb-sm-0 position-relative form-group row">
          <div class="col-lg-1 col-md-1"></div>

          <div class="control-label col-lg-3 col-md-3 col-sm-4 col-xs-12">
            <%= f.label :with_author, 'Search by Creator' %>
          </div>
          <div class="input-group col-lg-7 col-md-7 col-sm-8 col-xs-12">
          <%= f.text_field :with_author, class: "form-control" %>
          </div>
        </div>

        <div class="row" style="margin-top: 2em">
          <div class="col-lg-1 col-md-1"></div>
          <%= f.submit 'Search', class: "mb-2 mr-2  btn btn-primary" %>
        </div>
      <% end %>

      <div class='list'>
        <table class="mb-0 table table-striped table-hover">
          <thead>
          <tr>
            <th>Title</th>
            <th>Created By</th>
            <th>Description</th>
            <th>Fields</th>
          </tr>
          </thead>

          <tbody>
          <% @collaborations.each do |collaboration| %>
            <tr>
              <td><%= link_to collaboration.title, collaboration_path(collaboration) %></td>
              <td><%= collaboration.user.name %></td>
              <td><%= collaboration.description %></td>
              <td><%= collaboration.fields.join(', ') %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <%= render partial: 'partials/pagination', locals: {objects: @collaborations} %>
    </div>
  </div>
</div>

app/views/collaborations/new.html.erb
<div class="main-card mb-3 card mt-4">
  <div class="card-header">
    <div class="card-title">
      New Collaboration Request
    </div>
    <div style="margin-left: auto">
      <%= link_to 'Back', collaborations_path, class: "mb-2 mr-2 btn btn-primary"%>

    </div>
  </div>
  <div class="card-body">
    <%= render 'form', collaboration: @collaboration %>
  </div>
</div>

app/views/collaborations/show.html.erb
<p id="notice"><%= notice %></p>

<div class="main-card mb-3 card mt-4">
  <div class="card-header">
    <div class="card-title">
      <%= @collaboration.title %>
    </div>
    <div style="margin-left: auto">

      <% if current_user == @collaboration.user %>
        <%= link_to 'Edit', edit_collaboration_path(@collaboration), class: "mb-2 mr-2 btn-transition btn btn-outline-warning" %>
      <% else %>
        <%= link_to 'Contact', conversations_path(inviter_id: current_user.id, invitee_id: @collaboration.user.id), method: :post, class: 'mb-2 mr-2 btn-transistion btn btn-outline-warning' %>
        <%= link_to 'Profile', users_path(@collaboration.user), class: 'mb-2 mr-2 btn-transistion btn btn-outline-success' %>
      <% end %>
      <%= link_to 'Back', collaborations_path, class: "mb-2 mr-2  btn btn-primary" %>
    </div>
  </div>

  <div class="card-body">
    <p>
      <strong>By:</strong>
      <%= @collaboration.user.name %>
    </p>

    <p>
      <strong>Fields:</strong>
      <%= @collaboration.fields.join(',') %>
    </p>

    <p>
      <%= @collaboration.description %>
    </p>
  </div>
</div>